/* tslint:disable */
/* eslint-disable */
/**
 * auth.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface ActivateActivateCodeBody
 */
export interface ActivateActivateCodeBody {
    /**
     * 
     * @type {string}
     * @memberof ActivateActivateCodeBody
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof ActivateActivateCodeBody
     */
    pwd?: string;
    /**
     * 
     * @type {string}
     * @memberof ActivateActivateCodeBody
     */
    lang?: string;
}
