/* tslint:disable */
/* eslint-disable */
/**
 * auth.proto
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface AuthRefreshToken
 */
export interface AuthRefreshToken {
    /**
     * 
     * @type {number}
     * @memberof AuthRefreshToken
     */
    userId?: number;
    /**
     * 
     * @type {string}
     * @memberof AuthRefreshToken
     */
    token?: string;
    /**
     * 
     * @type {Date}
     * @memberof AuthRefreshToken
     */
    exp?: Date;
}
